version: '3.8'
services:
  thingsboard:
    image: thingsboard/tb-postgres:latest
    restart: always
    environment:
      TB_QUEUE_TYPE: in-memory
      HTTP_BIND_PORT: 9090
      SERVICE_FQDN_THINGSBOARD_9090 # Variável mágica do Coolify
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard
    expose:
      - "9090"
      - "1883"
    ports:
      - "1883:1883"
      - "5683-5688:5683-5688/udp"

volumes:
  tb-data:
  tb-logs:
