version: '3'
services:
  thingsboard:
    image: thingsboard/tb-postgres
    restart: always
    environment:
      - TB_QUEUE_TYPE=in-memory
      - TB_DB_HOST=postgres
      - TB_DB_PORT=5432
      - TB_DB_NAME=thingsboard
      - TB_DB_USERNAME=postgres
      - TB_DB_PASSWORD=${POSTGRES_PASSWORD}
      - HTTP_BIND_PORT=9090
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=thingsboard
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
