version: '3.8'
services:
  thingsboard:
    image: thingsboard/tb-postgres:latest
    restart: always
    environment:
      - TB_QUEUE_TYPE=${TB_QUEUE_TYPE:-in-memory}
      - TB_DB_HOST=${TB_DB_HOST:-postgres}
      - TB_DB_PORT=${TB_DB_PORT:-5432}
      - TB_DB_NAME=${TB_DB_NAME:-thingsboard}
      - TB_DB_USERNAME=${TB_DB_USERNAME:-postgres}
      - TB_DB_PASSWORD=${TB_DB_PASSWORD:-postgres}
      - HTTP_BIND_PORT=${HTTP_BIND_PORT:-9090}
      - SERVICE_FQDN_THINGSBOARD
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - tb-data:/data
      - tb-logs:/var/log/thingsboard
    labels:
      - traefik.enable=true
      - traefik.http.routers.thingsboard.rule=Host(`tb.hydradev.com.br`)
      - traefik.http.routers.thingsboard.entrypoints=websecure
      - traefik.http.routers.thingsboard.tls.certresolver=letsencrypt
      - traefik.http.services.thingsboard.loadbalancer.server.port=9090
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-thingsboard}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  tb-data:
  tb-logs:
  postgres-data:
