version: '3'

services:
  thingsboard:
    image: thingsboard/tb-postgres:3.9.1
    ports:
      - "9090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://coolify-db:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/PostgreSQL/data

volumes:
  postgres-data:
